services:
  backend:
    build:
      context: .
      target: development-image
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src/

  postgres:
    image: "postgres:16-alpine3.20"
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/pgdata
    environment:
      POSTGRES_PASSWORD: example
volumes:
  postgres:
    driver: local